import { useState } from 'react';
import styles from './ActionPlanTimeline.module.css';

const PRIORITY_COLORS = {
  high:   { color: 'var(--accent-rose)',  bg: 'rgba(244, 63, 94, 0.08)',   border: 'rgba(244, 63, 94, 0.2)' },
  medium: { color: 'var(--accent-amber)', bg: 'rgba(245, 158, 11, 0.08)',  border: 'rgba(245, 158, 11, 0.2)' },
  low:    { color: 'var(--accent-green)', bg: 'rgba(16, 185, 129, 0.08)', border: 'rgba(16, 185, 129, 0.2)' },
};

export default function ActionPlanTimeline({ steps = [], apiUrl }) {
  const [pushedSteps, setPushedSteps] = useState(new Set());
  const [pushingStep, setPushingStep] = useState(null);
  const [expandedStep, setExpandedStep] = useState(0);

  const handlePushToNotion = async (step) => {
    setPushingStep(step.step);
    try {
      const res = await fetch(`${apiUrl}/api/notion/task`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: step.title,
          description: step.description,
          priority: step.priority,
          estimatedHours: step.estimated_hours
        })
      });
      if (res.ok) {
        setPushedSteps(prev => new Set([...prev, step.step]));
      } else {
        const data = await res.json();
        alert('Notion push failed: ' + (data.error || 'Unknown error'));
      }
    } catch (err) {
      alert('Notion push failed: ' + err.message);
    } finally {
      setPushingStep(null);
    }
  };

  const totalHours = steps.reduce((sum, s) => sum + (s.estimated_hours || 0), 0);

  return (
    <div className={styles.wrapper}>
      {/* Header */}
      <div className={styles.header}>
        <div className={styles.headerLeft}>
          <h2 className={styles.title}>Your Personalized Roadmap</h2>
          <p className={styles.subtitle}>
            {steps.length} steps · ~{totalHours}h total
          </p>
        </div>
        <div className={styles.headerRight}>
          <div className={styles.coralBadge}>
            <span className={styles.coralDot} />
            Generated by Gemini + Coral
          </div>
        </div>
      </div>

      {/* Timeline */}
      <div className={styles.timeline}>
        {steps.map((step, i) => {
          const priority = PRIORITY_COLORS[step.priority] || PRIORITY_COLORS.medium;
          const isExpanded = expandedStep === i;
          const isPushed = pushedSteps.has(step.step);
          const isPushing = pushingStep === step.step;

          return (
            <div
              key={step.step}
              className={`${styles.step} ${isExpanded ? styles.stepExpanded : ''}`}
              style={{ animationDelay: `${i * 0.1}s` }}
            >
              {/* Connector line */}
              {i < steps.length - 1 && (
                <div className={styles.connector} aria-hidden="true" />
              )}

              {/* Step number bubble */}
              <div
                className={styles.stepBubble}
                style={{
                  background: priority.bg,
                  border: `2px solid ${priority.color}`,
                  color: priority.color,
                  boxShadow: `0 0 20px ${priority.bg}`
                }}
              >
                {step.step}
              </div>

              {/* Content */}
              <div
                className={styles.stepContent}
                onClick={() => setExpandedStep(isExpanded ? -1 : i)}
              >
                <div className={styles.stepTop}>
                  <div className={styles.stepMeta}>
                    <span
                      className={styles.priorityBadge}
                      style={{
                        color: priority.color,
                        background: priority.bg,
                        borderColor: priority.border
                      }}
                    >
                      {step.priority || 'medium'}
                    </span>
                    <span className={styles.hoursTag}>
                      ~{step.estimated_hours}h
                    </span>
                  </div>
                  <span className={styles.expandIcon}>
                    {isExpanded ? '▲' : '▼'}
                  </span>
                </div>

                <h3 className={styles.stepTitle}>{step.title}</h3>

                {isExpanded && (
                  <div className={styles.stepExpansion}>
                    <p className={styles.stepDescription}>{step.description}</p>

                    {step.resource && (
                      <div className={styles.resource}>
                        <span className={styles.resourceIcon}>📚</span>
                        <span className={styles.resourceText}>{step.resource}</span>
                      </div>
                    )}

                    <div className={styles.stepActions}>
                      <button
                        className={`${styles.notionBtn} ${isPushed ? styles.pushed : ''}`}
                        onClick={(e) => {
                          e.stopPropagation();
                          if (!isPushed) handlePushToNotion(step);
                        }}
                        disabled={isPushing}
                        id={`notion-push-${step.step}`}
                      >
                        {isPushing ? (
                          <>
                            <span className={styles.spinner} />
                            Adding to Notion...
                          </>
                        ) : isPushed ? (
                          <>✓ Added to Notion</>
                        ) : (
                          <>
                            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
                              <path d="M4 4a2 2 0 012-2h8l6 6v12a2 2 0 01-2 2H6a2 2 0 01-2-2V4z"/>
                            </svg>
                            Add to Notion
                          </>
                        )}
                      </button>
                    </div>
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Push all to Notion */}
      {steps.length > 0 && (
        <div className={styles.bulkAction}>
          <p className={styles.bulkText}>
            Push all {steps.length} steps to your Notion study tracker at once
          </p>
          <button
            className={styles.bulkBtn}
            id="push-all-notion"
            onClick={async () => {
              for (const step of steps) {
                if (!pushedSteps.has(step.step)) {
                  await handlePushToNotion(step);
                }
              }
            }}
          >
            📋 Push All to Notion
          </button>
        </div>
      )}
    </div>
  );
}
